default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres

development:
  <<: *default
  database: QueroRemoto_development

test:
  <<: *default
  database: QueroRemoto_test

production:
  <<: *default
  database: QueroRemoto_production
  username: QueroRemoto
  password: <%= ENV['QUEROREMOTO_DATABASE_PASSWORD'] %>
